### ISSUE TITLE
Shantae Risky's Revenge .tex extract and import!

### ISSUE THREAD

**Issue by jonastraducoes** [Banz99/LTBConverter#1]
I did the translation of the game, but unfortunately you can't edit the game images, could you help me with that?

**Comment by Banz99** [comment]
Please, try to keep in mind that Github issues should be related to the repository you are writing them in. Shantae Risky's Revenge, while being listed as a Wayforward Engine powered title, doesn't really use ltb files for the translation itself (which is located inside .loctext files instead), and even so, this has nothing to do with it. Nonetheless, given that you probably already know that, I'd suggest you contacting me on discord @ banz99#4857 for discussing texture stuff.

**Comment by jonastraducoes** [comment]
Ok, add you discord!
